[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "clerk-backend-api>=3.1.11",
    "fastapi>=0.116.1",
    "openai>=1.98.0",
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.42",
    "svix>=1.70.0",
    "together>=1.5.21",
    "uvicorn>=0.35.0",
]
